image: Visual Studio 2019
configuration: Release
platform: "Any CPU"

install:
  - choco install gitversion.portable -y

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - nuget restore
  - dotnet restore

build_script:
  - cmd: msbuild Cogito.sln /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%" /p:PackageOutputPath="%APPVEYOR_BUILD_FOLDER%\pkg"

artifacts:
  - path: pkg\*.nupkg
    name: Cogito

deploy:
  provider: NuGet
  server: https://nuget.pkg.github.com/wasabii/index.json
  username: wasabii
  api_key:
    secure: xrFuWmVqekabWUvYce7mOmKS4ToqdtFJOGgiLYyrDRVZJhMSMvpOUVxf0mhzwGiH
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
