image: Visual Studio 2017
configuration: Release
platform: "Any CPU"

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - nuget restore
  - dotnet restore

build_script:
  - cmd: msbuild Cogito.sln /p:Configuration=Release /p:Platform="Any CPU" /p:PackageOutputPath=$(APPVEYOR_BUILD_FOLDER)\Cogito\pkg

artifacts:
  - path: Cogito\pkg\*.nupkg
    name: Cogito
