//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("2013.9.21.916")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2013.9.21.916")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2013.9.21.916")]

